package     = "sysinvest"
description = "Python system monitor and investigation utility"
version     = "0.8.9"
date        = "26 July 2023"
author      = "Marc Bertens-Nguyen"
author_email= "m.bertens@pe2mbs.nl"
copyright   = "Copyright (C) 2022-2023 Marc Bertens-Nguyen m.bertens@pe2mbs.nl"
licence     = "GPL2-only"
