package     = "sysinvest"
description = "Python system monitor and investigation utility"
version     = "0.11.22"
date        = "5 July 2024"
author      = "Marc Bertens-Nguyen"
author_email= "m.bertens@pe2mbs.nl"
copyright   = "Copyright (C) 2022-2024 Marc Bertens-Nguyen m.bertens@pe2mbs.nl"
licence     = "GPL2-only"
